### DISCUSSION TITLE
[Feature/playbook/key.ops] - How to install and uninstall public keys to remote servers

### DISCUSSION THREAD

**Discussion by piyoki** [TechProber/cloud-estate#100] [General]
## Objective

This dicussion demonstrates how you can install and uninstall `gpg-public-key` using ansible playbook.

## Associated PR

[Patch/playbooks/key.ops] - Better key management - #99

### Step 0 - Prepare your inventory list

```yaml
# server.yml
---
server:
  hosts:
    test-server:
      ansible_host: 10.178.0.65
      ansible_user: packer
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
```

### Step 1 - Prepare your playbooks

```yaml
# install-new-key.yml
---
- name: Install new ssh key
  hosts: all

  vars:
    - public_keys:
      - ~/.ssh/id_rsa_yubikey.pub
    - operation: add
  roles:
    - role: ../../roles/maintenance.ops/key.ops/
```

```yaml
# uninstall-existing-keys.yml
- name: Uninstall existing ssh key(s)
  hosts: all

  vars:
    - public_keys:
      - ~/.ssh/id_rsa.pub
      - ~/.ssh/ansible_id_rsa.pub
    - operation: remove
  roles:
    - role: ../../roles/maintenance.ops/key.ops/
```

### Step 2 - Run the playbook to install the gpg public key

```bash
ansible-playbook -K -i ~/.local/inventory/server.yml ~/workspace/cloud-estate/ansible-playbooks/playbooks/playbooks/maintenance/install-new-key.yml
```

### Step 3 (Optional) - Run the playbook to uninstall the existing(old) public key

```bash
ansible-playbook -K -i ~/.local/inventory/server.yml ~/workspace/cloud-estate/ansible-playbooks/playbooks/playbooks/maintenance/uninstall-existing-key.yml
```
